//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoggyStyleWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdoptionRequest
    {
        public int AdoptionRequestId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PetIdAdoptionId { get; set; }
        public string State { get; set; }
    
        public virtual PetAdoption PetAdoption { get; set; }
        public virtual User User { get; set; }
    }
}
