//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoggyStyleWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int PetId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string NamePet { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
        public int Type { get; set; }
        public string SpecialFeatures { get; set; }
        public Nullable<int> PetShelterId { get; set; }
        public int Age { get; set; }
        public string ImagenUrl { get; set; }
    
        public virtual PetShelter PetShelter { get; set; }
        public virtual User User { get; set; }
        public virtual PetImage PetImage { get; set; }
    }
}
