//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoggyStyleWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetImage
    {
        public int PetImageId { get; set; }
        public int PetId { get; set; }
        public string ImageUrl { get; set; }
        public string State { get; set; }
    
        public virtual Pet Pet { get; set; }
    }
}
