//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoggyStyleWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetShelterImage
    {
        public int PetShelterImage1 { get; set; }
        public int PetShelterId { get; set; }
        public int ImageUrl { get; set; }
        public string State { get; set; }
    
        public virtual PetShelter PetShelter { get; set; }
    }
}
